app:
  repository:
    provider: mongodb

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rxmongodb

logging:
  level:
    root: info
    org.bwg.rxmongodb: debug
