version: '3.9'

services:

  #
  #  Zoo Keeper
  #
#  zoo1:
#    image: zookeeper:3.7.0
#    restart: always
#    hostname: zoo1
#    networks:
#      broker-bridge:
#        ipv4_address: 172.18.0.11
#    ports:
#      - "2181:2181"
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zoo1:2888:3888
#    volumes:
#      - ./kafka/zoo1/data:/data
#      - ./kafka/zoo1/datalog:/datalog

  zoo1:
    image: kymeric/cp-zookeeper:latest
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./kafka/zoo1/data:/data
      - ./kafka/zoo1/datalog:/datalog
    extra_hosts:
      - "moby:127.0.0.1"
      - "localhost: 127.0.0.1"


  #
  #  Kafka Broker 1
  #
#  kafka1:
#    image: brett/kafka:latest
#    hostname: kafka1
#    ports:
#      - "9091:9091"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
#      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
#      KAFKA_BROKER_ID: 1
#      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#    volumes:
#      - ./kafka/kafka1/data:/var/lib/kafka/data
#    depends_on:
#      - zoo1

  #
  #  Kafka Broker 2
  #
#  kafka2:
#    image: confluentinc/cp-kafka:5.3.0
#    hostname: kafka2
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
#      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:2181"
#      KAFKA_BROKER_ID: 2
#      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#    volumes:
#      - ./broker/kafka2/data:/var/lib/kafka/data
#    depends_on:
#      - zoo

  #
  #  Kafka Broker 3
  #
#  kafka3:
#    image: confluentinc/cp-kafka:5.3.0
#    hostname: kafka3
#    ports:
#      - "9093:9093"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
#      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:2181"
#      KAFKA_BROKER_ID: 3
#      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#    volumes:
#      - ./broker/kafka3/data:/var/lib/kafka/data
#    depends_on:
#      - zoo

  #
  #  Zoo Keeper Manager
  #
#  manager:
#    image: sheepkiller/kafka-manager
#    ports:
#      - 9000:9000
#    environment:
#      - ZK_HOSTS=zoo:2181
#    depends_on:
#      - zoo

#  zoonavigator:
#    image: elkozmon/zoonavigator
#    ports:
#      - 9000:9000
#    extra_hosts:
#      - "moby:127.0.0.1"
#      - "localhost: 127.0.0.1"

#networks:
#  broker-bridge:
#    external:
#      name: broker